### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by oggminator**
1. Handling for `InvalidSequenceTokenException` (multiple instances running / logging in the same time on the same stream -> concurrency)
2. Attach handlers to different writable stream events
3. Emit an event once the logs are successfully push / save in AWS CloudWatch

### CODE REVIEW

**Review by thorstenHemann — APPROVED** [review]

**Comment by dbhowell** [comment]
I'm of the understanding that multiple instances should not write to a single stream, they should be separate streams in the same log group.

Would you agree?

**Comment by oggminator** [comment]
> I'm of the understanding that multiple instances should not write to a single stream, they should be separate streams in the same log group.
> 
> Would you agree?

I would let this decision open for everyone (is more like an architectural approach based on project / infrastructure / business nature and needs).

I would suggest not to enforce this within the package / cloudwatch streamer flow and let it open and versatil / flexible.


Checking the AWS CloudWatch Logs docs here: https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html

there is no enforced constraint regarding this.

There is more like a note / mention (somehow related to concurrency):

`If you call PutLogEvents twice within a narrow time period using the same value for sequenceToken, both calls might be successful or one might be rejected.`

Thank you!

**Comment by dbhowell** [comment]
Good point, thank you!

**Comment by dbhowell** [comment]
Is there any point in having the `write_complete_event` CLI parameter? If using the CLI you wouldn't be able to listen to the event anyway?

**Comment by oggminator** [comment]
> Is there any point in having the `write_complete_event` CLI parameter? If using the CLI you wouldn't be able to listen to the event anyway?

Good point, I'll remove it from the supported CLI parameters list.

**Comment by dbhowell** [comment]
Sorry for additional questions, what is the value in having the write_complete_event event name configurable?

Would it be better to use a standard event name (like `complete` or `flushed`) and emit regardless? Then the errorHandler option/interface wouldn't need to change?

**Comment by oggminator** [comment]
> Is there any point in having the `write_complete_event` CLI parameter? If using the CLI you wouldn't be able to listen to the event anyway?

Done!

**Comment by oggminator** [comment]
> Sorry for additional questions, what is the value in having the write_complete_event event name configurable?
> 
> Would it be better to use a standard event name (like `complete` or `flushed`) and emit regardless? Then the errorHandler option/interface wouldn't need to change?

1. Regarding having the write_complete_event event name configurable:

Is more like giving the implementer the possibility to "customize" the package... to make it somehow more "personal" :)
I do also agree that we could go by choosing an exact event name and emit regardless ... I would kindly ask you to take the final decision on this (please let me know the way we should proceed with)

2. Then the errorHandler option/interface wouldn't need to change:

The real reason why we updated this to `events` is that that will give the implementer the possibility to custom handle specific streamer emitted events (if desired) more than the `error` one (a reference to `unpipe` was added within README.md file).
Using this to also subscribe and handle to `write_complete_event` is more like an outcome :)

**Comment by oggminator** [comment]
Hello,

We switched to your above suggestion and removed the custom `write_complete_event` event support. We do also added a standard event name `flushed` that fires anytime once the logs are successfully pushed to AWS CloudWatch Logs.

We need to go live with our application and I'll kindly ask for your review since we rely on these enhancements to get published :)

Thank you!

**Comment by dbhowell** [comment]
Hello, I'm going to break this into two PRs if that is OK. Also, since `pino-cloudwatch` currently returns the `stdout`, if we change that to return `log` (`CloudWatchStream`) then you can just `.on()` for events directly rather than pass event handlers through the config.

**Comment by oggminator** [comment]
> Hello, I'm going to break this into two PRs if that is OK. Also, since `pino-cloudwatch` currently returns the `stdout`, if we change that to return `log` (`CloudWatchStream`) then you can just `.on()` for events directly rather than pass event handlers through the config.

That would be awesome :) ... will you make this update or should we push a new PR commit including that?

**Comment by oggminator** [comment]
> Hello, I'm going to break this into two PRs if that is OK. Also, since `pino-cloudwatch` currently returns the `stdout`, if we change that to return `log` (`CloudWatchStream`) then you can just `.on()` for events directly rather than pass event handlers through the config.

I see you point but, for example:

**Comment by dbhowell** [comment]
I'll put them up and you can look over them before I merge. I'll link them here when done.

**Comment by oggminator** [comment]
> I'll put them up and you can look over them before I merge. I'll link them here when done.

Yet the following question, please correct me if I'm wrong:

We want to be able to flush and final push on demand calling `stdout.push(null)` or `stdout.end()` ... this will automatically trigger the flush and will end up pushing the buffer `on demand`.

... by directly returning the `log (CloudWatchStream)` instead... this option will not be available anymore :(

**Comment by dbhowell** [comment]
I see why you've designed it this way now! :-)

**Comment by oggminator** [comment]
> I see why you've designed it this way now! :-)

Sorry for not introducing you the general context from the very beginning ... lesson learned 💯

Now that we both are on the same page, how should we proceed next? :)

**Comment by dbhowell** [comment]
I thought I could possibly return a duplex stream (using `duplexer`) that is both `stdout` (Readable) and `log` (Writable) but that doesn't seem to work.

**Comment by dbhowell** [comment]
I've published `v0.7.0` in `npm`. I scrapped the `events` object, but bubbled the `flushed` event to the `stdout` so you should be able to `.on()` to get the events you need.

I think the `errorHandler` should work in the same way, but I don't want to break changes yet.

Let me know how you go!

**Comment by oggminator** [comment]
Hi,

We'd successfully pull the new `v0.7.0` and accordingly implemented it! Everything works as expected :)

Thank you very much!

**Pull request closed without merging**
